global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "banvetau-prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: "/metrics"

  - job_name: "banvetau-springboot"
    scrape_interval: 15s
    static_configs:
      - targets: [ "host.docker.internal:6677"]
    metrics_path: "/actuator/prometheus"

  - job_name: "banvetau-node-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "banvetau-mysql-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: [ "host.docker.internal:9114" ]
    metrics_path: "/metrics"

  - job_name: "banvetau-redis-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: [ "host.docker.internal:9121" ]
    metrics_path: "/metrics"
