services:
  mysql:
    image: mysql:9.2.0
    container_name: pre-event-mysql
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
#        '--skip-character-set-client-handshake' #was removed from mysql 9
    ]

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ticket
      MYSQL_PASSWORD: root1234
      MYSQL_USER: win
    ports:
      - "3306:3306"
    networks:
      - pre-event-network

  redis:
    container_name: pre-event-redis
    image: redislabs/redismod:latest
    ports:
      - "6389:6379"
    networks:
      - pre-event-network

  prometheus:
    image: prom/prometheus:latest
    container_name: pre-event-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - pre-event-network
networks:
  pre-event-network:
    driver: bridge